-- Used copilot to generate much of this code using text defining our database schema
CREATE TABLE
    Users (
        id INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        first_name VARCHAR(255) NOT NULL,
        last_name VARCHAR(255) NOT NULL,
        email VARCHAR UNIQUE NOT NULL,
        password VARCHAR(255) NOT NULL,
        address VARCHAR(255),
        balance DECIMAL
    );

CREATE TABLE
    Products (
        id INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        name VARCHAR(255) NOT NULL,
        short_name VARCHAR(255),
        description VARCHAR(1024),
        image_src VARCHAR(255),
        creator_id INT REFERENCES Users (id)
    );

CREATE TABLE
    Categories (
        id INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        name VARCHAR(255) NOT NULL,
        left_idx INT,
        right_idx INT,
        level INT
    );

CREATE TABLE
    ProductCategory (
        id INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        category_id INT REFERENCES Categories (id)
    );

CREATE TABLE
    ProductReviews (
        uid INT REFERENCES Users (id),
        pid INT REFERENCES Products (id),
        rating INT,
        text VARCHAR(255),
        review_date TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT (current_timestamp AT TIME ZONE 'UTC'),
        PRIMARY KEY (uid, pid)
    );

CREATE TABLE
    SellerReviews (
        buyer_id INT REFERENCES Users (id),
        sid INT REFERENCES Users (id),
        rating INT,
        text VARCHAR(255),
        review_date TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT (current_timestamp AT TIME ZONE 'UTC'),
        PRIMARY KEY (buyer_id, sid)
    );

CREATE TABLE
    Inventory (
        id INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        sid INT REFERENCES Users (id),
        pid INT REFERENCES Products (id),
        quantity INT,
        price DECIMAL(12, 2),
        modified_date TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT (current_timestamp AT TIME ZONE 'UTC'),
        promo_code VARCHAR(255)
    );

CREATE TABLE
    Cart (
        uid INT REFERENCES Users (id),
        pid INT REFERENCES Products (id),
        sid INT REFERENCES Users (id),
        price DECIMAL(12, 2),
        quantity INT,
        promo_code VARCHAR(255),
        PRIMARY KEY (uid, pid, sid)
    );

CREATE TABLE
    SaveForLater (
        uid INT REFERENCES Users (id),
        pid INT REFERENCES Products (id),
        sid INT REFERENCES Users (id),
        price DECIMAL(12, 2),
        quantity INT,
        promo_code VARCHAR(255),
        PRIMARY KEY (uid, pid, sid)
    );

CREATE TABLE
    Orderline (
        id INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        customer_id INT REFERENCES Users (id),
        pid INT REFERENCES Products (id),
        sid INT REFERENCES Users (id),
        order_id INT,
        quantity INT,
        cost_per_item INT,
        fulfillment_status BOOLEAN,
        purchase_date TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT (current_timestamp AT TIME ZONE 'UTC'),
        modified_date TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT (current_timestamp AT TIME ZONE 'UTC')
    );